name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please verify that you have checked the following before submitting an issue
      options:
        - label: I have searched the [issue list](https://github.com/jwcam/MunicipalityManagementSystem/issues) to see if this issue is already reported
          required: true
        - label: I have verified that I am on the latest version of the application
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: "The application crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Navigate to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "The page should display the citizen details..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead
      placeholder: "The page throws a NullReferenceException..."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "You can drag and drop images here"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: Windows 11
        - .NET Version: 10.0.0
        - SQL Server Version: 2022
        - Browser: Chrome 120
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: "This bug occurs intermittently when..."
    validations:
      required: false
